#minecraft:is_river > null
#minecraft:is_beach > aeroscapes:void_shores

#minecraft:is_deep_ocean > aeroscapes:deep_voidsea

#minecraft:is_ocean > aeroscapes:voidsea

minecraft:deep_frozen_ocean > aeroscapes:deep_voidsea
minecraft:deep_cold_ocean > aeroscapes:deep_voidsea
minecraft:deep_ocean > aeroscapes:deep_voidsea
minecraft:deep_lukewarm_ocean > aeroscapes:deep_voidsea

minecraft:frozen_ocean > aeroscapes:voidsea
minecraft:ocean > aeroscapes:voidsea
minecraft:cold_ocean > aeroscapes:voidsea
minecraft:lukewarm_ocean > aeroscapes:voidsea
minecraft:warm_ocean > aeroscapes:voidsea

minecraft:ice_spikes > terralith:glacial_chasm
minecraft:eroded_badlands > minecraft:badlands

natures_spirit:stratified_desert > minecraft:wooded_badlands
natures_spirit:white_cliffs > null
natures_spirit:sugi_forest > null
natures_spirit:blooming_sugi_forest > null
natures_spirit:blooming_dunes > null
natures_spirit:lively_dunes > null
natures_spirit:windswept_sugi_forest > null
natures_spirit:snowy_fir_forest > natures_spirit:tundra

#terralith:skylands > null
terralith:alpha_islands > null
terralith:alpha_islands_winter > null
terralith:bryce_canyon > null
terralith:cloud_forest > null
terralith:scarlet_mountains > null
terralith:warm_river > null
terralith:warped_mesa > null

terralith:cave/deep_caves > galosphere:lichen_caves
terralith:cave/andesite_caves > galosphere:pink_salt_caves
terralith:cave/granite_caves > galosphere:lichen_caves
terralith:cave/infested_caves > minecraft:deep_dark
terralith:cave/diorite_caves > galosphere:crystal_canyons
terralith:cave/frostfire_caves > minecraft:dripstone_caves
terralith:cave/tuff_caves > minecraft:dripstone_caves
terralith:cave/underground_jungle > minecraft:lush_caves

terralith:jungle_mountains > aeroscapes:fractured_jungle