#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.betterend]
			dragon_tree = true
			end_lotus = true
			helix_tree = true
			jellyshroom = true
			lacugrove = true
			lucernia = true
			mossy_glowshroom = true
			pythadendron = true
			tenanea = true
			umbrella_tree = true

		[types.wood_type.betternether]
			anchor_tree = true
			mushroom_fir = true
			nether_mushroom = true
			nether_reed = true
			nether_sakura = true
			rubeus = true
			stalagnate = true
			wart = true
			willow = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.leaves_type.betterend]
			dragon_tree = true
			lacugrove = true
			lucernia = true
			pythadendron = true
			tenanea = true

		[types.leaves_type.betternether]
			anchor_tree = true
			nether_sakura = true
			rubeus = true
			willow = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

#Disables specific entries
[entries]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			chest = true
			stripped_post = true
			ladder = true
			trapped_chest = true
			bookshelf = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true
