items {
    # Format: "modid:item_name"=durability
    # Examples:
    # "minecraft:diamond_sword"=750
    # "minecraft:netherite_sword"=1250
    # "minecraft:trident"=325
	"vc_gliders:paraglider_wood"=500
}
